[[EDFlib]]
arch = "aarch64"
git-tree-sha1 = "c1f6c02cf3b775048e82718303eb57a1c3f3256a"
libc = "musl"
os = "linux"

    [[EDFlib.download]]
    sha256 = "e782053d99796dba0ff64f767d06b20f1984f964afbd8598f844ad41fc1fca49"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.aarch64-linux-musl.tar.gz"
[[EDFlib]]
arch = "i686"
git-tree-sha1 = "874bc41046c52d05ddbe429c6723d094e7fab3c6"
os = "windows"

    [[EDFlib.download]]
    sha256 = "72f6cebc7d667940d32f69b9f2e3878dd19b1cd1a584445f9fd0219356955652"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.i686-w64-mingw32.tar.gz"
[[EDFlib]]
arch = "x86_64"
git-tree-sha1 = "55959f3ade76975b489bb544d1b773644f7b1522"
libc = "musl"
os = "linux"

    [[EDFlib.download]]
    sha256 = "5a4f57d7a0aaac6d630926a83fe14a87ef3113f7d32498f3dca95d301e62601c"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.x86_64-linux-musl.tar.gz"
[[EDFlib]]
arch = "i686"
git-tree-sha1 = "eeb3487ea7f175b32dc4ba7f7def04f5f4738fda"
libc = "glibc"
os = "linux"

    [[EDFlib.download]]
    sha256 = "9a6667dce5af77270f461ade77d33c8a97245b3d4ec789d2f6769be68de5514e"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.i686-linux-gnu.tar.gz"
[[EDFlib]]
arch = "armv7l"
git-tree-sha1 = "21316539938626bca4a4565c32b26eeb1b5c8a6a"
libc = "glibc"
os = "linux"

    [[EDFlib.download]]
    sha256 = "dd2c6639ce025c06a484ef3f53c81be1c5e9380eed8aafea01d03d86fa2ae153"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.armv7l-linux-gnueabihf.tar.gz"
[[EDFlib]]
arch = "aarch64"
git-tree-sha1 = "b03f2aca59985554a84d9b4d9d808be5d4007368"
libc = "glibc"
os = "linux"

    [[EDFlib.download]]
    sha256 = "b5c07ac068833a6d3195b8960778c22e57db42c4fcd5dbf240806c6990595a96"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.aarch64-linux-gnu.tar.gz"
[[EDFlib]]
arch = "x86_64"
git-tree-sha1 = "00cbc671ef8b514e2fc019ea7b025e79a416f4f0"
libc = "glibc"
os = "linux"

    [[EDFlib.download]]
    sha256 = "272ba71a8d0978628d8bc84cd02cad274ea454861c9d8c2411cc678c13618b81"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.x86_64-linux-gnu.tar.gz"
[[EDFlib]]
arch = "powerpc64le"
git-tree-sha1 = "0ec8d7ae6823c0ff4cd70273a286e85bf1e02ede"
libc = "glibc"
os = "linux"

    [[EDFlib.download]]
    sha256 = "fadcbf1cbdee1c613abfccbdfe285a004b83f5d0a8c57267f4d84c22284d0b26"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.powerpc64le-linux-gnu.tar.gz"
[[EDFlib]]
arch = "x86_64"
git-tree-sha1 = "7ce9aab7080db81e01fba9931a8d75f25a818072"
os = "macos"

    [[EDFlib.download]]
    sha256 = "78f33d9d5a16666ebae10e8feb6751cbb7796ffab634b1d0f3cdd95ba2a89444"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.x86_64-apple-darwin14.tar.gz"
[[EDFlib]]
arch = "x86_64"
git-tree-sha1 = "2353208ffe537c3031fbb4cecf4e630475365560"
os = "freebsd"

    [[EDFlib.download]]
    sha256 = "345b26e56993c8b427a276b3a3c4333b07839c511a255dbc8f58fc6fefe9fb45"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.x86_64-unknown-freebsd11.1.tar.gz"
[[EDFlib]]
arch = "i686"
git-tree-sha1 = "339c7741f7aac7b493fe4fd28ce8a8da7656535f"
libc = "musl"
os = "linux"

    [[EDFlib.download]]
    sha256 = "b4d5ec685ea5b8e897339c29fa3d0aee1549e38ac2df7c7a2c3d9a6b86437a24"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.i686-linux-musl.tar.gz"
[[EDFlib]]
arch = "armv7l"
git-tree-sha1 = "796d8df0d824b2c383354b16a8578d9abcd92940"
libc = "musl"
os = "linux"

    [[EDFlib.download]]
    sha256 = "00d33a233732fbb26cfc632a99db6de08acba8f7f943916069df8688dc5a59b6"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.armv7l-linux-musleabihf.tar.gz"
[[EDFlib]]
arch = "x86_64"
git-tree-sha1 = "2345844ae49f8320535274e6435a44e951766bc8"
os = "windows"

    [[EDFlib.download]]
    sha256 = "b59941b5b35324f01079de15337aa8743a0353ef27c8b81048e05b5b0e87e663"
    url = "https://github.com/JuliaBinaryWrappers/EDFlib_jll.jl/releases/download/EDFlib-v1.16.0+1/EDFlib.v1.16.0.x86_64-w64-mingw32.tar.gz"
